repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.0
    hooks:
      - id: prettier
        types_or: [markdown]

  - repo: local
    hooks:
      - id: go-fmt
        name: Run go fmt
        language: golang
        types: [go]
        entry: go fmt
